// Booking Statuses - NO optional chaining
export const BOOKING_STATUSES = {
    INQUIRY: 'inquiry',
    UNDER_REVIEW: 'under_review',
    AWAITING_DOCUMENTS: 'awaiting_documents',
    DOCUMENTS_PENDING: 'documents_pending',
    MEDICAL_REVIEW_PENDING: 'medical_review_pending',
    ACCEPTED: 'accepted',
    REJECTED: 'rejected',
    QUOTATION_PENDING: 'quotation_pending',
    QUOTATION_SENT: 'quotation_sent',
    AWAITING_MEDICAL_DETAILS: 'awaiting_medical_details',
    PAYMENT_PENDING: 'payment_pending',
    PAYMENT_COMPLETED: 'payment_completed',
    INVOICE_SENT: 'invoice_sent',
    TRAVEL_ARRANGEMENT: 'travel_arrangement',
    TRAVEL_CONFIRMED: 'travel_confirmed',
    IN_TREATMENT: 'in_treatment',
    COMPLETED: 'completed',
    FEEDBACK_RECEIVED: 'feedback_received',
    CANCELLED: 'cancelled',
    ON_HOLD: 'on_hold',
};

export const BOOKING_STATUS_FLOW = {
    inquiry: [BOOKING_STATUSES.UNDER_REVIEW, BOOKING_STATUSES.REJECTED],
    under_review: [BOOKING_STATUSES.AWAITING_DOCUMENTS, BOOKING_STATUSES.REJECTED],
    awaiting_documents: [BOOKING_STATUSES.DOCUMENTS_PENDING, BOOKING_STATUSES.REJECTED],
    documents_pending: [BOOKING_STATUSES.MEDICAL_REVIEW_PENDING, BOOKING_STATUSES.REJECTED],
    medical_review_pending: [BOOKING_STATUSES.ACCEPTED, BOOKING_STATUSES.REJECTED],
    accepted: [BOOKING_STATUSES.QUOTATION_PENDING],
    quotation_pending: [BOOKING_STATUSES.QUOTATION_SENT],
    quotation_sent: [BOOKING_STATUSES.PAYMENT_PENDING],
    payment_pending: [BOOKING_STATUSES.PAYMENT_COMPLETED, BOOKING_STATUSES.CANCELLED],
    payment_completed: [BOOKING_STATUSES.INVOICE_SENT],
    invoice_sent: [BOOKING_STATUSES.TRAVEL_ARRANGEMENT],
    travel_arrangement: [BOOKING_STATUSES.TRAVEL_CONFIRMED],
    travel_confirmed: [BOOKING_STATUSES.IN_TREATMENT],
    in_treatment: [BOOKING_STATUSES.COMPLETED],
    completed: [BOOKING_STATUSES.FEEDBACK_RECEIVED],
    feedback_received: [],
    cancelled: [],
    rejected: [],
    on_hold: [BOOKING_STATUSES.INQUIRY],
};