// composables/useDataMock.js
export const useDataMock = () => {
  const generateMockDataEntries = () => {
    return [
      {
        id: 1,
        type: "patient",
        title: "Patient Medical Records - John Doe",
        description:
          "Complete medical history and treatment records for patient ID 1234",
        category: "medical",
        status: "active",
        priority: "normal",
        size: 2458752, // bytes
        createdAt: "2025-10-14T08:30:00Z",
        updatedAt: "2025-10-14T09:15:00Z",
        createdBy: "Dr. Smith",
        lastModifiedBy: "Nurse Wilson",
        tags: ["cardiology", "chronic", "medication"],
        metadata: {
          patientId: 1234,
          patientName: "John Doe",
          recordCount: 45,
          fileCount: 12,
          imageCount: 8,
          lastVisit: "2025-10-10T14:30:00Z",
          department: "Cardiology",
        },
        data: {
          demographics: { age: 65, gender: "M", bloodType: "O+" },
          vitals: { bp: "140/90", hr: "72 bpm", temp: "98.6°F" },
          conditions: ["Hypertension", "Diabetes Type 2"],
          medications: ["Metformin", "Lisinopril", "Aspirin"],
          allergies: ["Penicillin", "Latex"],
        },
        permissions: {
          read: ["admin", "doctor", "nurse"],
          write: ["admin", "doctor"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 10,
          autoDelete: false,
          archiveAfter: 3,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: false,
          consentRequired: true,
          hipaaCompliant: true,
          lastAudit: "2025-10-01T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-14T02:00:00Z",
          backupCount: 15,
          backupSize: 2458752,
          autoBackup: true,
        },
      },
      {
        id: 2,
        type: "lab",
        title: "Laboratory Results - Blood Work Panel",
        description:
          "Complete blood chemistry and hematology results for multiple patients",
        category: "lab",
        status: "active",
        priority: "high",
        size: 1256789,
        createdAt: "2025-10-14T07:00:00Z",
        updatedAt: "2025-10-14T08:45:00Z",
        createdBy: "Lab System",
        lastModifiedBy: "Lab Tech Johnson",
        tags: ["blood-work", "chemistry", "hematology", "critical"],
        metadata: {
          labId: "LAB-2025-001",
          testCount: 156,
          patientCount: 42,
          criticalResults: 3,
          pendingReview: 8,
          department: "Laboratory",
        },
        data: {
          testTypes: ["CBC", "CMP", "Lipid Panel", "HbA1c", "TSH"],
          criticalValues: [
            {
              patient: "Jane Smith",
              test: "Glucose",
              value: 450,
              critical: true,
            },
            {
              patient: "Bob Wilson",
              test: "Creatinine",
              value: 3.2,
              critical: true,
            },
          ],
          equipment: ["Analyzer-A1", "Analyzer-B2", "Microscope-M3"],
          qualityControl: { passed: 154, failed: 2, retest: 1 },
        },
        permissions: {
          read: ["admin", "doctor", "nurse", "lab_tech"],
          write: ["admin", "lab_tech"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 7,
          autoDelete: false,
          archiveAfter: 2,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: false,
          consentRequired: false,
          hipaaCompliant: true,
          lastAudit: "2025-10-10T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-14T01:00:00Z",
          backupCount: 22,
          backupSize: 1256789,
          autoBackup: true,
        },
      },
      {
        id: 3,
        type: "appointment",
        title: "Appointment Scheduling Data",
        description:
          "Patient appointment records, scheduling conflicts, and availability data",
        category: "appointment",
        status: "active",
        priority: "normal",
        size: 856432,
        createdAt: "2025-10-13T15:20:00Z",
        updatedAt: "2025-10-14T07:30:00Z",
        createdBy: "Scheduling System",
        lastModifiedBy: "Receptionist Mary",
        tags: ["scheduling", "calendar", "availability"],
        metadata: {
          appointmentCount: 284,
          todayAppointments: 23,
          upcomingAppointments: 156,
          canceledAppointments: 12,
          rescheduledAppointments: 8,
          departments: ["Cardiology", "Dermatology", "Orthopedics"],
        },
        data: {
          timeSlots: ["09:00", "09:30", "10:00", "10:30", "11:00"],
          doctorSchedules: {
            "Dr. Smith": { available: true, nextFree: "2025-10-15T10:00:00Z" },
            "Dr. Wilson": {
              available: false,
              nextFree: "2025-10-16T14:00:00Z",
            },
          },
          roomAvailability: {
            "Room A-101": true,
            "Room B-205": false,
            "Room C-312": true,
          },
        },
        permissions: {
          read: ["admin", "doctor", "nurse", "receptionist"],
          write: ["admin", "receptionist"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 5,
          autoDelete: true,
          archiveAfter: 1,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: false,
          consentRequired: false,
          hipaaCompliant: true,
          lastAudit: "2025-09-15T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-14T03:00:00Z",
          backupCount: 8,
          backupSize: 856432,
          autoBackup: true,
        },
      },
      {
        id: 4,
        type: "billing",
        title: "Patient Billing and Insurance Data",
        description:
          "Billing records, insurance claims, payment history, and financial data",
        category: "billing",
        status: "active",
        priority: "high",
        size: 3245678,
        createdAt: "2025-10-12T09:00:00Z",
        updatedAt: "2025-10-14T08:00:00Z",
        createdBy: "Billing System",
        lastModifiedBy: "Billing Manager",
        tags: ["insurance", "payments", "claims", "financial"],
        metadata: {
          totalClaims: 156,
          pendingClaims: 23,
          approvedClaims: 121,
          rejectedClaims: 12,
          totalRevenue: 245000,
          outstandingBalance: 45000,
          departments: ["All"],
        },
        data: {
          insuranceProviders: [
            "Aetna",
            "Blue Cross",
            "Cigna",
            "Medicare",
            "Medicaid",
          ],
          paymentMethods: ["Cash", "Credit Card", "Check", "Insurance"],
          billingCodes: ["99213", "99214", "99215", "36415", "80053"],
          recentTransactions: [
            {
              amount: 150,
              patient: "John Doe",
              date: "2025-10-14",
              status: "paid",
            },
            {
              amount: 75,
              patient: "Jane Smith",
              date: "2025-10-13",
              status: "pending",
            },
          ],
        },
        permissions: {
          read: ["admin", "billing"],
          write: ["admin", "billing"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 7,
          autoDelete: false,
          archiveAfter: 2,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: false,
          consentRequired: true,
          hipaaCompliant: true,
          lastAudit: "2025-10-05T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-14T00:30:00Z",
          backupCount: 28,
          backupSize: 3245678,
          autoBackup: true,
        },
      },
      {
        id: 5,
        type: "system",
        title: "System Configuration and Logs",
        description:
          "Application settings, error logs, performance metrics, and system health data",
        category: "system",
        status: "active",
        priority: "critical",
        size: 4567890,
        createdAt: "2025-10-11T00:00:00Z",
        updatedAt: "2025-10-14T10:30:00Z",
        createdBy: "System",
        lastModifiedBy: "Admin",
        tags: ["configuration", "logs", "monitoring", "performance"],
        metadata: {
          configFiles: 23,
          errorLogs: 156,
          warningLogs: 489,
          infoLogs: 2341,
          uptime: "99.97%",
          lastReboot: "2025-10-10T02:00:00Z",
          activeConnections: 45,
        },
        data: {
          services: {
            Database: { status: "healthy", uptime: "99.99%", connections: 12 },
            "API Server": {
              status: "healthy",
              uptime: "99.98%",
              requests: 15432,
            },
            "File Storage": {
              status: "warning",
              uptime: "99.85%",
              usage: "78%",
            },
          },
          performance: {
            cpuUsage: "23%",
            memoryUsage: "67%",
            diskUsage: "45%",
            networkTraffic: "1.2 GB/day",
          },
          security: {
            failedLogins: 3,
            blockedIPs: ["192.168.1.100", "10.0.0.50"],
            lastSecurityScan: "2025-10-13T02:00:00Z",
          },
        },
        permissions: {
          read: ["admin"],
          write: ["admin"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 3,
          autoDelete: true,
          archiveAfter: 1,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: true,
          consentRequired: false,
          hipaaCompliant: false,
          lastAudit: "2025-10-01T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-14T04:00:00Z",
          backupCount: 35,
          backupSize: 4567890,
          autoBackup: true,
        },
      },
      {
        id: 6,
        type: "medical",
        title: "Medical Imaging Archives",
        description:
          "X-rays, CT scans, MRIs, ultrasounds, and other medical imaging data",
        category: "imaging",
        status: "active",
        priority: "high",
        size: 15678901,
        createdAt: "2025-10-10T12:00:00Z",
        updatedAt: "2025-10-14T06:45:00Z",
        createdBy: "Radiology System",
        lastModifiedBy: "Dr. Radiologist",
        tags: ["imaging", "radiology", "dicom", "xray", "mri"],
        metadata: {
          imageCount: 567,
          studyCount: 89,
          patientCount: 67,
          modalities: ["CT", "MRI", "X-Ray", "Ultrasound"],
          urgentReports: 5,
          pendingReports: 12,
        },
        data: {
          storage: {
            total: "500 GB",
            used: "387 GB",
            free: "113 GB",
            compression: "enabled",
          },
          qualityMetrics: {
            imageQuality: "excellent",
            compressionRatio: "8:1",
            viewingErrors: 0,
            accessTime: "< 2 seconds",
          },
          recentStudies: [
            {
              patient: "Alice Johnson",
              type: "CT Chest",
              date: "2025-10-14",
              urgent: true,
            },
            {
              patient: "Bob Smith",
              type: "MRI Brain",
              date: "2025-10-13",
              urgent: false,
            },
          ],
        },
        permissions: {
          read: ["admin", "doctor", "radiologist"],
          write: ["admin", "radiologist"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 15,
          autoDelete: false,
          archiveAfter: 5,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: false,
          consentRequired: true,
          hipaaCompliant: true,
          lastAudit: "2025-09-20T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-14T01:30:00Z",
          backupCount: 12,
          backupSize: 15678901,
          autoBackup: true,
        },
      },
      {
        id: 7,
        type: "pharmacy",
        title: "Pharmacy and Medication Data",
        description:
          "Drug inventory, prescriptions, dispensing records, and drug interaction data",
        category: "pharmacy",
        status: "active",
        priority: "normal",
        size: 987654,
        createdAt: "2025-10-09T14:00:00Z",
        updatedAt: "2025-10-14T09:00:00Z",
        createdBy: "Pharmacy System",
        lastModifiedBy: "Pharmacist Johnson",
        tags: ["medications", "prescriptions", "inventory", "drugs"],
        metadata: {
          prescriptionCount: 234,
          drugCount: 1567,
          lowStockItems: 12,
          expiredMedications: 3,
          totalDispensed: 189,
          pendingRefills: 45,
        },
        data: {
          inventory: {
            totalItems: 1567,
            inStock: 1552,
            lowStock: 12,
            outOfStock: 3,
            expired: 3,
          },
          topMedications: [
            { name: "Metformin", prescribed: 45, inStock: 500 },
            { name: "Lisinopril", prescribed: 32, inStock: 300 },
            { name: "Aspirin", prescribed: 28, inStock: 1000 },
          ],
          interactions: {
            checked: 234,
            warnings: 8,
            contraindications: 2,
            allergies: 5,
          },
        },
        permissions: {
          read: ["admin", "doctor", "pharmacy"],
          write: ["admin", "pharmacy"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 7,
          autoDelete: false,
          archiveAfter: 2,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: false,
          consentRequired: true,
          hipaaCompliant: true,
          lastAudit: "2025-09-25T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-14T02:30:00Z",
          backupCount: 18,
          backupSize: 987654,
          autoBackup: true,
        },
      },
      {
        id: 8,
        type: "archived",
        title: "Archived Patient Records 2020-2022",
        description:
          "Historical patient data archived for compliance and reference purposes",
        category: "medical",
        status: "archived",
        priority: "low",
        size: 8901234,
        createdAt: "2020-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
        createdBy: "Archive System",
        lastModifiedBy: "Data Manager",
        tags: ["archived", "historical", "compliance", "reference"],
        metadata: {
          patientCount: 1234,
          recordCount: 5678,
          yearRange: "2020-2022",
          archiveDate: "2023-01-01",
          compressionRatio: "12:1",
          indexedFiles: 5678,
        },
        data: {
          archiveStats: {
            originalSize: "107 GB",
            compressedSize: "8.9 GB",
            compressionRatio: "12:1",
            integrityChecks: "passed",
          },
          accessLog: {
            lastAccessed: "2025-08-15T10:30:00Z",
            accessCount: 23,
            authorizedUsers: ["admin", "compliance_officer"],
          },
          retentionInfo: {
            minimumRetention: "7 years",
            scheduledDeletion: "2027-01-01",
            legalHold: false,
          },
        },
        permissions: {
          read: ["admin", "compliance_officer"],
          write: ["admin"],
          delete: ["admin"],
        },
        retention: {
          keepFor: 7,
          autoDelete: true,
          archiveAfter: 0,
        },
        compliance: {
          encrypted: true,
          auditTrail: true,
          anonymized: true,
          consentRequired: false,
          hipaaCompliant: true,
          lastAudit: "2025-07-01T00:00:00Z",
        },
        backup: {
          lastBackup: "2025-10-01T00:00:00Z",
          backupCount: 4,
          backupSize: 8901234,
          autoBackup: false,
        },
      },
    ];
  };

  const generateDataCategories = () => {
    return [
      { value: "medical", label: "Medical Records", icon: "🏥", color: "red" },
      {
        value: "patient",
        label: "Patient Information",
        icon: "👤",
        color: "green",
      },
      {
        value: "appointment",
        label: "Appointments",
        icon: "📅",
        color: "purple",
      },
      {
        value: "billing",
        label: "Billing & Insurance",
        icon: "💰",
        color: "emerald",
      },
      {
        value: "lab",
        label: "Laboratory Results",
        icon: "🧪",
        color: "orange",
      },
      { value: "pharmacy", label: "Pharmacy Data", icon: "💊", color: "pink" },
      { value: "imaging", label: "Medical Imaging", icon: "🔬", color: "blue" },
      {
        value: "system",
        label: "System Configuration",
        icon: "⚙️",
        color: "slate",
      },
      { value: "audit", label: "Audit Logs", icon: "📋", color: "yellow" },
      { value: "backup", label: "Backup Data", icon: "💾", color: "gray" },
    ];
  };

  const generatePermissionRoles = () => {
    return [
      { value: "admin", label: "Administrator", color: "red" },
      { value: "doctor", label: "Doctor", color: "blue" },
      { value: "nurse", label: "Nurse", color: "green" },
      { value: "receptionist", label: "Receptionist", color: "purple" },
      { value: "lab_tech", label: "Lab Technician", color: "orange" },
      { value: "billing", label: "Billing Staff", color: "emerald" },
      { value: "pharmacy", label: "Pharmacy Staff", color: "pink" },
      { value: "radiologist", label: "Radiologist", color: "indigo" },
      {
        value: "compliance_officer",
        label: "Compliance Officer",
        color: "yellow",
      },
    ];
  };

  const generateExportFormats = () => {
    return [
      {
        value: "csv",
        label: "CSV",
        icon: "📄",
        description: "Comma-separated values",
      },
      {
        value: "excel",
        label: "Excel (XLSX)",
        icon: "📊",
        description: "Microsoft Excel format",
      },
      {
        value: "json",
        label: "JSON",
        icon: "{ }",
        description: "JavaScript Object Notation",
      },
      {
        value: "xml",
        label: "XML",
        icon: "🔖",
        description: "Extensible Markup Language",
      },
      {
        value: "pdf",
        label: "PDF Report",
        icon: "📑",
        description: "Formatted PDF document",
      },
      {
        value: "sql",
        label: "SQL Dump",
        icon: "🗄️",
        description: "Database export",
      },
      {
        value: "hl7",
        label: "HL7",
        icon: "🏥",
        description: "Health Level 7 format",
      },
      {
        value: "dicom",
        label: "DICOM",
        icon: "🔬",
        description: "Medical imaging format",
      },
    ];
  };

  const generateBackupHistory = () => {
    return [
      {
        id: 1,
        date: "2025-10-14T02:00:00Z",
        type: "full",
        status: "completed",
        size: 45678901,
        duration: "2h 15m",
        records: 8542,
        location: "AWS S3",
        checksum: "a1b2c3d4e5f6",
      },
      {
        id: 2,
        date: "2025-10-13T02:00:00Z",
        type: "incremental",
        status: "completed",
        size: 5678901,
        duration: "23m",
        records: 234,
        location: "AWS S3",
        checksum: "b2c3d4e5f6a1",
      },
      {
        id: 3,
        date: "2025-10-12T02:00:00Z",
        type: "incremental",
        status: "completed",
        size: 3456789,
        duration: "18m",
        records: 156,
        location: "AWS S3",
        checksum: "c3d4e5f6a1b2",
      },
    ];
  };

  const generateAuditLogs = () => {
    return [
      {
        id: 1,
        timestamp: "2025-10-14T09:15:00Z",
        action: "data_access",
        user: "dr.smith@hospital.com",
        resource: "patient_record_1234",
        details: "Accessed patient John Doe medical records",
        ipAddress: "192.168.1.100",
        userAgent: "Chrome 118.0.0.0",
        result: "success",
      },
      {
        id: 2,
        timestamp: "2025-10-14T09:10:00Z",
        action: "data_export",
        user: "admin@hospital.com",
        resource: "lab_results_batch",
        details: "Exported 156 lab results to CSV",
        ipAddress: "192.168.1.101",
        userAgent: "Chrome 118.0.0.0",
        result: "success",
      },
    ];
  };

  return {
    generateMockDataEntries,
    generateDataCategories,
    generatePermissionRoles,
    generateExportFormats,
    generateBackupHistory,
    generateAuditLogs,
  };
};
