// composables/useHospitalMock.js
import { ref } from "vue";

export const useHospitalMock = () => {
  const hospitals = ref([
    {
      id: 1,
      name: "Mayo Clinic",
      type: "Multi-specialty",
      address: "200 First St SW",
      city: "Rochester",
      state: "Minnesota",
      country: "United States",
      phone: "+1-507-284-2511",
      email: "info@mayo.edu",
      established: "01/01/1889",
      totalBeds: 1265,
      availableBeds: 189,
      totalDoctors: 4500,
      departments: [
        "Cardiology",
        "Neurology",
        "Oncology",
        "Orthopedics",
        "Gastroenterology",
      ],
      status: "Active",
    },
    {
      id: 2,
      name: "Johns Hopkins Hospital",
      type: "Teaching Hospital",
      address: "1800 Orleans St",
      city: "Baltimore",
      state: "Maryland",
      country: "United States",
      phone: "+1-410-955-5000",
      email: "contact@jhmi.edu",
      established: "07/05/1889",
      totalBeds: 1154,
      availableBeds: 267,
      totalDoctors: 3200,
      departments: [
        "Cardiac Surgery",
        "Neurosurgery",
        "Oncology",
        "Pediatrics",
        "Emergency Medicine",
      ],
      status: "Active",
    },
    {
      id: 3,
      name: "Singapore General Hospital",
      type: "Government Hospital",
      address: "Outram Rd",
      city: "Singapore",
      state: "Central Region",
      country: "Singapore",
      phone: "+65-6222-3322",
      email: "corporate@sgh.com.sg",
      established: "01/01/1821",
      totalBeds: 1785,
      availableBeds: 234,
      totalDoctors: 1800,
      departments: [
        "Medicine",
        "Surgery",
        "Cardiology",
        "Neurology",
        "Oncology",
      ],
      status: "Active",
    },
    {
      id: 4,
      name: "Charité - Universitätsmedizin Berlin",
      type: "University Hospital",
      address: "Charitéplatz 1",
      city: "Berlin",
      state: "Berlin",
      country: "Germany",
      phone: "+49-30-450-50",
      email: "info@charite.de",
      established: "09/01/1710",
      totalBeds: 3001,
      availableBeds: 445,
      totalDoctors: 4500,
      departments: [
        "Internal Medicine",
        "Surgery",
        "Neurology",
        "Pediatrics",
        "Radiology",
      ],
      status: "Active",
    },
    {
      id: 5,
      name: "The University of Tokyo Hospital",
      type: "University Hospital",
      address: "7-3-1 Hongo, Bunkyo-ku",
      city: "Tokyo",
      state: "Tokyo",
      country: "Japan",
      phone: "+81-3-3815-5411",
      email: "info@h.u-tokyo.ac.jp",
      established: "15/06/1858",
      totalBeds: 1210,
      availableBeds: 178,
      totalDoctors: 2100,
      departments: [
        "Medicine",
        "Surgery",
        "Pediatrics",
        "Obstetrics",
        "Psychiatry",
      ],
      status: "Active",
    },
    {
      id: 6,
      name: "Toronto General Hospital",
      type: "Teaching Hospital",
      address: "200 Elizabeth St",
      city: "Toronto",
      state: "Ontario",
      country: "Canada",
      phone: "+1-416-340-4800",
      email: "info@uhn.ca",
      established: "12/03/1812",
      totalBeds: 727,
      availableBeds: 123,
      totalDoctors: 2800,
      departments: [
        "Cardiology",
        "Transplant Surgery",
        "Oncology",
        "Neurology",
        "Emergency",
      ],
      status: "Active",
    },
    {
      id: 7,
      name: "Great Ormond Street Hospital",
      type: "Pediatric Specialty Hospital",
      address: "Great Ormond St",
      city: "London",
      state: "England",
      country: "United Kingdom",
      phone: "+44-20-7405-9200",
      email: "communications@gosh.nhs.uk",
      established: "14/02/1852",
      totalBeds: 395,
      availableBeds: 67,
      totalDoctors: 1200,
      departments: [
        "Pediatric Surgery",
        "Pediatric Cardiology",
        "Neurology",
        "Oncology",
        "Critical Care",
      ],
      status: "Active",
    },
    {
      id: 8,
      name: "Karolinska University Hospital",
      type: "University Hospital",
      address: "171 76 Stockholm",
      city: "Stockholm",
      state: "Stockholm County",
      country: "Sweden",
      phone: "+46-8-517-700-00",
      email: "info@karolinska.se",
      established: "01/01/1940",
      totalBeds: 1600,
      availableBeds: 289,
      totalDoctors: 3000,
      departments: [
        "Medicine",
        "Surgery",
        "Oncology",
        "Neurology",
        "Pediatrics",
      ],
      status: "Active",
    },
    {
      id: 9,
      name: "Apollo Hospitals",
      type: "Multi-specialty",
      address: "21, Greams Lane",
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
      phone: "+91-44-2829-3333",
      email: "info@apollohospitals.com",
      established: "15/09/1983",
      totalBeds: 550,
      availableBeds: 89,
      totalDoctors: 120,
      departments: [
        "Cardiology",
        "Neurology",
        "Oncology",
        "Orthopedics",
        "Gastroenterology",
      ],
      status: "Active",
    },
    {
      id: 10,
      name: "Bumrungrad International Hospital",
      type: "Private International Hospital",
      address: "33 Sukhumvit 3",
      city: "Bangkok",
      state: "Bangkok",
      country: "Thailand",
      phone: "+66-2-066-8888",
      email: "info@bumrungrad.com",
      established: "01/07/1980",
      totalBeds: 580,
      availableBeds: 134,
      totalDoctors: 1200,
      departments: [
        "Cardiology",
        "Orthopedics",
        "Oncology",
        "Neurology",
        "Cosmetic Surgery",
      ],
      status: "Active",
    },
    {
      id: 11,
      name: "Hospital Israelita Albert Einstein",
      type: "Private Hospital",
      address: "Av. Albert Einstein, 627",
      city: "São Paulo",
      state: "São Paulo",
      country: "Brazil",
      phone: "+55-11-2151-1233",
      email: "contato@einstein.br",
      established: "02/05/1971",
      totalBeds: 692,
      availableBeds: 145,
      totalDoctors: 2500,
      departments: [
        "Cardiology",
        "Oncology",
        "Neurology",
        "Orthopedics",
        "Emergency Medicine",
      ],
      status: "Active",
    },
    {
      id: 12,
      name: "Chris Hani Baragwanath Hospital",
      type: "Public Hospital",
      address: "26 Chris Hani Rd, Diepkloof",
      city: "Soweto",
      state: "Gauteng",
      country: "South Africa",
      phone: "+27-11-933-0720",
      email: "info@chbah.org.za",
      established: "01/12/1942",
      totalBeds: 3200,
      availableBeds: 456,
      totalDoctors: 1800,
      departments: [
        "Medicine",
        "Surgery",
        "Pediatrics",
        "Obstetrics",
        "Emergency Medicine",
      ],
      status: "Active",
    },
    {
      id: 13,
      name: "Prince Court Medical Centre",
      type: "Private Hospital",
      address: "39 Jalan Kia Peng",
      city: "Kuala Lumpur",
      state: "Federal Territory",
      country: "Malaysia",
      phone: "+60-3-2160-0999",
      email: "info@princecourt.com",
      established: "25/09/2007",
      totalBeds: 270,
      availableBeds: 67,
      totalDoctors: 600,
      departments: [
        "Cardiology",
        "Oncology",
        "Neurology",
        "Orthopedics",
        "Gastroenterology",
      ],
      status: "Active",
    },
    {
      id: 14,
      name: "American Hospital of Paris",
      type: "Private International Hospital",
      address: "63 Bd Victor Hugo",
      city: "Neuilly-sur-Seine",
      state: "Île-de-France",
      country: "France",
      phone: "+33-1-46-41-25-25",
      email: "info@american-hospital.org",
      established: "04/07/1906",
      totalBeds: 187,
      availableBeds: 34,
      totalDoctors: 400,
      departments: [
        "Medicine",
        "Surgery",
        "Cardiology",
        "Oncology",
        "Emergency Medicine",
      ],
      status: "Active",
    },
    {
      id: 15,
      name: "King Faisal Specialist Hospital",
      type: "Specialty Hospital",
      address: "Maather St",
      city: "Riyadh",
      state: "Riyadh Province",
      country: "Saudi Arabia",
      phone: "+966-11-464-7272",
      email: "info@kfshrc.edu.sa",
      established: "01/01/1975",
      totalBeds: 1200,
      availableBeds: 234,
      totalDoctors: 2200,
      departments: [
        "Oncology",
        "Organ Transplant",
        "Cardiac Sciences",
        "Neurosciences",
        "Genetics",
      ],
      status: "Active",
    },
    {
      id: 16,
      name: "Fortis Hospital",
      type: "Multi-specialty",
      address: "Sector 62, Phase VIII",
      city: "Mohali",
      state: "Punjab",
      country: "India",
      phone: "+91-172-496-7000",
      email: "contact@fortishealthcare.com",
      established: "20/03/2001",
      totalBeds: 355,
      availableBeds: 67,
      totalDoctors: 85,
      departments: [
        "Cardiac Sciences",
        "Neurosciences",
        "Orthopedics",
        "Oncology",
      ],
      status: "Active",
    },
  ]);

  const addHospital = (data) => {
    const newId =
      (hospitals.value.length
        ? Math.max(...hospitals.value.map((h) => h.id))
        : 0) + 1;

    hospitals.value.unshift({
      id: newId,
      ...data,
      totalDoctors: 0, // New hospital starts with 0 doctors
    });
  };

  const updateHospital = (updated) => {
    const i = hospitals.value.findIndex((h) => h.id === updated.id);
    if (i > -1) hospitals.value[i] = { ...updated };
  };

  const removeHospital = (id) => {
    const i = hospitals.value.findIndex((h) => h.id === id);
    if (i > -1) hospitals.value.splice(i, 1);
  };

  const getHospitalById = (id) => {
    return hospitals.value.find((h) => h.id === id);
  };

  // Get unique countries for filtering
  const getCountries = () => {
    const countries = [...new Set(hospitals.value.map((h) => h.country))];
    return countries.sort();
  };

  // Get hospitals by country
  const getHospitalsByCountry = (country) => {
    return hospitals.value.filter((h) => h.country === country);
  };

  return {
    hospitals,
    addHospital,
    updateHospital,
    removeHospital,
    getHospitalById,
    getCountries,
    getHospitalsByCountry,
  };
};
