// composables/useInsuranceMock.js
import { ref, computed } from 'vue';

export const useInsuranceMock = () => {
  const insurances = ref([
    {
      id: 1,
      companyName: 'Allianz Care',
      companyLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200',
      country: 'Germany',
      region: 'Europe',
      planName: 'Global Health Plus',
      planType: 'comprehensive',
      coverageAmount: 5000000,
      currency: 'USD',
      premium: 2500,
      deductible: 1000,
      coinsurance: 20,
      copay: 50,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: false,
      },
      networkSize: 15000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 30,
      contactPerson: {
        name: 'Sarah Johnson',
        email: 'sarah.j@allianzcare.com',
        phone: '+49 89 1234 5678',
        position: 'Senior Account Manager',
      },
      status: 'active',
      totalPolicies: 1247,
      activePolicies: 1156,
      claimSettlementRatio: 96.8,
      avgClaimSettlementTime: 5,
      customerRating: 4.7,
      reviewCount: 892,
      isPopular: true,
      isFeatured: true,
      commission: 15,
      partneredSince: '2020-03-15',
      benefits: [
        'Worldwide coverage',
        '24/7 Emergency assistance',
        'Direct billing with network hospitals',
        'Telemedicine included',
      ],
      exclusions: [
        'Pre-existing conditions (first 2 years)',
        'Cosmetic procedures',
        'Experimental treatments',
      ],
      documents: [
        { name: 'Policy Brochure', type: 'pdf', url: '#', size: '2.5 MB' },
        { name: 'Terms & Conditions', type: 'pdf', url: '#', size: '1.8 MB' },
      ],
      tags: ['comprehensive', 'global', 'family-friendly'],
    },
    {
      id: 2,
      companyName: 'Cigna Global',
      companyLogo: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=200',
      country: 'United States',
      region: 'Americas',
      planName: 'International Health Premium',
      planType: 'premium',
      coverageAmount: 10000000,
      currency: 'USD',
      premium: 4200,
      deductible: 500,
      coinsurance: 10,
      copay: 30,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 25000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 0,
      contactPerson: {
        name: 'Michael Chen',
        email: 'm.chen@cigna.com',
        phone: '+1 860 123 4567',
        position: 'International Sales Director',
      },
      status: 'active',
      totalPolicies: 2341,
      activePolicies: 2187,
      claimSettlementRatio: 98.2,
      avgClaimSettlementTime: 3,
      customerRating: 4.9,
      reviewCount: 1456,
      isPopular: true,
      isFeatured: true,
      commission: 18,
      partneredSince: '2018-06-20',
      benefits: [
        'Unlimited lifetime coverage',
        'Worldwide coverage including USA',
        'Zero waiting period',
        'Mental health support 24/7',
      ],
      exclusions: ['Cosmetic surgery', 'Fertility treatments'],
      documents: [{ name: 'Policy Document', type: 'pdf', url: '#', size: '3.2 MB' }],
      tags: ['premium', 'usa-coverage', 'unlimited'],
    },
    {
      id: 3,
      companyName: 'Bupa Global',
      companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=200',
      country: 'United Kingdom',
      region: 'Europe',
      planName: 'Essential International',
      planType: 'basic',
      coverageAmount: 2000000,
      currency: 'GBP',
      premium: 1800,
      deductible: 2000,
      coinsurance: 30,
      copay: 75,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: false,
        vision: false,
        maternity: false,
        mentalHealth: false,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: false,
      },
      networkSize: 8000,
      networkType: 'regional',
      claimProcess: 'reimbursement',
      waitingPeriod: 90,
      contactPerson: {
        name: 'Emma Williams',
        email: 'e.williams@bupa.com',
        phone: '+44 20 1234 5678',
        position: 'Account Manager',
      },
      status: 'active',
      totalPolicies: 876,
      activePolicies: 789,
      claimSettlementRatio: 94.5,
      avgClaimSettlementTime: 7,
      customerRating: 4.3,
      reviewCount: 543,
      isPopular: false,
      isFeatured: false,
      commission: 12,
      partneredSince: '2019-11-10',
      benefits: [
        'Europe and Asia coverage',
        'Emergency medical evacuation',
        'Prescription drug coverage',
      ],
      exclusions: ['Pre-existing conditions', 'Dental and vision care', 'Maternity services'],
      documents: [{ name: 'Policy Guide', type: 'pdf', url: '#', size: '1.5 MB' }],
      tags: ['basic', 'affordable', 'regional'],
    },
    {
      id: 4,
      companyName: 'AXA Global Healthcare',
      companyLogo: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=200',
      country: 'France',
      region: 'Europe',
      planName: 'World Select',
      planType: 'premium',
      coverageAmount: 8000000,
      currency: 'EUR',
      premium: 3800,
      deductible: 750,
      coinsurance: 15,
      copay: 40,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 18000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 15,
      contactPerson: {
        name: 'Pierre Dubois',
        email: 'p.dubois@axa.com',
        phone: '+33 1 4567 8900',
        position: 'Regional Sales Manager',
      },
      status: 'active',
      totalPolicies: 1543,
      activePolicies: 1432,
      claimSettlementRatio: 97.5,
      avgClaimSettlementTime: 4,
      customerRating: 4.8,
      reviewCount: 1032,
      isPopular: true,
      isFeatured: true,
      commission: 16,
      partneredSince: '2021-01-25',
      benefits: [
        'Global coverage with USA optional',
        'Cancer screening programs',
        'Wellness and fitness benefits',
        'Second medical opinion service',
      ],
      exclusions: ['War and terrorism', 'Self-inflicted injuries'],
      documents: [{ name: 'Policy Handbook', type: 'pdf', url: '#', size: '2.8 MB' }],
      tags: ['premium', 'family', 'wellness', 'global'],
    },
    {
      id: 5,
      companyName: 'IMG Global',
      companyLogo: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=200',
      country: 'United States',
      region: 'Americas',
      planName: 'Patriot International',
      planType: 'comprehensive',
      coverageAmount: 1000000,
      currency: 'USD',
      premium: 1200,
      deductible: 500,
      coinsurance: 20,
      copay: 45,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: false,
        vision: false,
        maternity: false,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: false,
        rehabilitation: false,
      },
      networkSize: 12000,
      networkType: 'global',
      claimProcess: 'reimbursement',
      waitingPeriod: 60,
      contactPerson: {
        name: 'Robert Martinez',
        email: 'r.martinez@imglobal.com',
        phone: '+1 317 555 4500',
        position: 'Sales Executive',
      },
      status: 'active',
      totalPolicies: 634,
      activePolicies: 598,
      claimSettlementRatio: 93.7,
      avgClaimSettlementTime: 6,
      customerRating: 4.4,
      reviewCount: 387,
      isPopular: false,
      isFeatured: false,
      commission: 13,
      partneredSince: '2022-08-12',
      benefits: [
        'Short-term international coverage',
        'Sports and adventure activities covered',
        'Political evacuation included',
      ],
      exclusions: ['Routine physicals', 'Dental and vision', 'Pre-existing conditions'],
      documents: [{ name: 'Plan Details', type: 'pdf', url: '#', size: '1.9 MB' }],
      tags: ['travel', 'sports', 'flexible'],
    },
    {
      id: 6,
      companyName: 'Aetna International',
      companyLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200',
      country: 'United States',
      region: 'Americas',
      planName: 'Global Choice',
      planType: 'premium',
      coverageAmount: 15000000,
      currency: 'USD',
      premium: 5500,
      deductible: 250,
      coinsurance: 5,
      copay: 25,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 30000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 0,
      contactPerson: {
        name: 'Jennifer Lee',
        email: 'j.lee@aetna.com',
        phone: '+1 800 123 4567',
        position: 'Executive Account Manager',
      },
      status: 'active',
      totalPolicies: 3456,
      activePolicies: 3289,
      claimSettlementRatio: 99.1,
      avgClaimSettlementTime: 2,
      customerRating: 4.9,
      reviewCount: 2145,
      isPopular: true,
      isFeatured: true,
      commission: 20,
      partneredSince: '2017-04-05',
      benefits: [
        'Highest coverage limit',
        'Worldwide coverage including USA',
        'Personalized care coordination',
        'Health concierge service',
      ],
      exclusions: ['Experimental treatments only'],
      documents: [
        { name: 'Policy Document', type: 'pdf', url: '#', size: '4.2 MB' },
        { name: 'Benefit Schedule', type: 'pdf', url: '#', size: '2.1 MB' },
      ],
      tags: ['premium', 'luxury', 'unlimited', 'concierge'],
    },
    {
      id: 7,
      companyName: 'Zurich International',
      companyLogo: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=200',
      country: 'Switzerland',
      region: 'Europe',
      planName: 'Swiss Care Plus',
      planType: 'premium',
      coverageAmount: 6500000,
      currency: 'CHF',
      premium: 4800,
      deductible: 1500,
      coinsurance: 20,
      copay: 60,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 22000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 10,
      contactPerson: {
        name: 'Klaus Weber',
        email: 'k.weber@zurich.com',
        phone: '+41 44 628 2811',
        position: 'International Director',
      },
      status: 'active',
      totalPolicies: 1876,
      activePolicies: 1743,
      claimSettlementRatio: 97.8,
      avgClaimSettlementTime: 4,
      customerRating: 4.6,
      reviewCount: 823,
      isPopular: true,
      isFeatured: false,
      commission: 17,
      partneredSince: '2019-07-15',
      benefits: [
        'Swiss quality healthcare',
        'Preventive wellness programs',
        'Global emergency coverage',
      ],
      exclusions: ['War zones', 'Nuclear incidents'],
      documents: [{ name: 'Policy Terms', type: 'pdf', url: '#', size: '3.1 MB' }],
      tags: ['swiss', 'premium', 'wellness'],
    },
    {
      id: 8,
      companyName: 'William Russell',
      companyLogo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=200',
      country: 'United Kingdom',
      region: 'Europe',
      planName: 'Expat Health Plus',
      planType: 'premium',
      coverageAmount: 7500000,
      currency: 'GBP',
      premium: 4500,
      deductible: 600,
      coinsurance: 12,
      copay: 30,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 28000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 0,
      contactPerson: {
        name: 'Oliver Smith',
        email: 'o.smith@williamrussell.com',
        phone: '+44 1372 808 740',
        position: 'Senior Consultant',
      },
      status: 'active',
      totalPolicies: 2108,
      activePolicies: 1987,
      claimSettlementRatio: 98.5,
      avgClaimSettlementTime: 3,
      customerRating: 4.8,
      reviewCount: 1234,
      isPopular: true,
      isFeatured: true,
      commission: 19,
      partneredSince: '2018-11-30',
      benefits: [
        'Expatriate specialists',
        'Global coverage',
        'Concierge medical service',
        'Mental health support',
      ],
      exclusions: ['War zones', 'Space travel'],
      documents: [{ name: 'Expat Guide', type: 'pdf', url: '#', size: '4.1 MB' }],
      tags: ['expat', 'premium', 'concierge', 'global'],
    },
    {
      id: 9,
      companyName: 'Pacific Cross',
      companyLogo: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=200',
      country: 'Thailand',
      region: 'Asia Pacific',
      planName: 'Asia Health Shield',
      planType: 'comprehensive',
      coverageAmount: 3000000,
      currency: 'USD',
      premium: 2200,
      deductible: 800,
      coinsurance: 15,
      copay: 35,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: false,
        maternity: true,
        mentalHealth: false,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 12500,
      networkType: 'regional',
      claimProcess: 'cashless',
      waitingPeriod: 45,
      contactPerson: {
        name: 'Ananya Patel',
        email: 'a.patel@pacificcross.com',
        phone: '+66 2 665 3333',
        position: 'Regional Manager',
      },
      status: 'active',
      totalPolicies: 945,
      activePolicies: 876,
      claimSettlementRatio: 95.2,
      avgClaimSettlementTime: 6,
      customerRating: 4.4,
      reviewCount: 564,
      isPopular: false,
      isFeatured: true,
      commission: 14,
      partneredSince: '2021-03-22',
      benefits: [
        'Asia-Pacific coverage',
        'Medical tourism benefits',
        'Traditional medicine coverage',
      ],
      exclusions: ['Mental health', 'High-risk sports'],
      documents: [{ name: 'Policy Booklet', type: 'pdf', url: '#', size: '2.8 MB' }],
      tags: ['asia', 'comprehensive', 'medical-tourism'],
    },
    {
      id: 10,
      companyName: 'Generali Global Health',
      companyLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=200',
      country: 'Italy',
      region: 'Europe',
      planName: 'Mediterranean Care',
      planType: 'comprehensive',
      coverageAmount: 4200000,
      currency: 'EUR',
      premium: 3100,
      deductible: 900,
      coinsurance: 18,
      copay: 45,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 16800,
      networkType: 'global',
      claimProcess: 'both',
      waitingPeriod: 20,
      contactPerson: {
        name: 'Marco Rossi',
        email: 'm.rossi@generali.com',
        phone: '+39 06 4411 8800',
        position: 'International Sales Manager',
      },
      status: 'active',
      totalPolicies: 1234,
      activePolicies: 1156,
      claimSettlementRatio: 96.3,
      avgClaimSettlementTime: 5,
      customerRating: 4.5,
      reviewCount: 678,
      isPopular: true,
      isFeatured: false,
      commission: 15,
      partneredSince: '2020-09-08',
      benefits: ['European excellence', 'Comprehensive family coverage', 'Wellness programs'],
      exclusions: ['Extreme sports', 'Experimental treatments'],
      documents: [{ name: 'Policy Manual', type: 'pdf', url: '#', size: '3.5 MB' }],
      tags: ['european', 'comprehensive', 'family'],
    },
    {
      id: 11,
      companyName: 'MSH International',
      companyLogo: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=200',
      country: 'Canada',
      region: 'Americas',
      planName: 'World Nomad',
      planType: 'basic',
      coverageAmount: 1500000,
      currency: 'CAD',
      premium: 1650,
      deductible: 1200,
      coinsurance: 25,
      copay: 80,
      coverage: {
        inpatient: true,
        outpatient: false,
        emergency: true,
        dental: false,
        vision: false,
        maternity: false,
        mentalHealth: false,
        prescriptionDrugs: true,
        preventiveCare: false,
        rehabilitation: false,
      },
      networkSize: 7500,
      networkType: 'regional',
      claimProcess: 'reimbursement',
      waitingPeriod: 120,
      contactPerson: {
        name: 'David Thompson',
        email: 'd.thompson@msh.com',
        phone: '+1 416 555 0123',
        position: 'Account Executive',
      },
      status: 'active',
      totalPolicies: 432,
      activePolicies: 398,
      claimSettlementRatio: 92.1,
      avgClaimSettlementTime: 8,
      customerRating: 4.0,
      reviewCount: 287,
      isPopular: false,
      isFeatured: false,
      commission: 10,
      partneredSince: '2023-01-10',
      benefits: ['Emergency coverage', 'Inpatient care', 'Prescription drugs'],
      exclusions: ['Outpatient care', 'Dental', 'Vision', 'Maternity'],
      documents: [{ name: 'Basic Plan Details', type: 'pdf', url: '#', size: '1.2 MB' }],
      tags: ['basic', 'emergency', 'budget'],
    },
    {
      id: 12,
      companyName: 'GeoBlue',
      companyLogo: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=200',
      country: 'United States',
      region: 'Americas',
      planName: 'Voyager Choice',
      planType: 'comprehensive',
      coverageAmount: 2500000,
      currency: 'USD',
      premium: 1980,
      deductible: 750,
      coinsurance: 20,
      copay: 40,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: false,
        vision: false,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: false,
      },
      networkSize: 14200,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 30,
      contactPerson: {
        name: 'Lisa Rodriguez',
        email: 'l.rodriguez@geoblue.com',
        phone: '+1 855 481 6647',
        position: 'Travel Health Specialist',
      },
      status: 'active',
      totalPolicies: 756,
      activePolicies: 712,
      claimSettlementRatio: 94.8,
      avgClaimSettlementTime: 5,
      customerRating: 4.3,
      reviewCount: 445,
      isPopular: false,
      isFeatured: false,
      commission: 13,
      partneredSince: '2022-05-18',
      benefits: ['Travel medicine focus', 'Emergency evacuation', 'Telemedicine 24/7'],
      exclusions: ['Dental', 'Vision', 'Cosmetic procedures'],
      documents: [{ name: 'Travel Health Guide', type: 'pdf', url: '#', size: '2.4 MB' }],
      tags: ['travel', 'comprehensive', 'telemedicine'],
    },
    {
      id: 13,
      companyName: 'April International',
      companyLogo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=200',
      country: 'France',
      region: 'Europe',
      planName: 'Carte Blanche',
      planType: 'premium',
      coverageAmount: 9000000,
      currency: 'EUR',
      premium: 5200,
      deductible: 400,
      coinsurance: 8,
      copay: 20,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 32000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 0,
      contactPerson: {
        name: 'Amélie Dubois',
        email: 'a.dubois@april.com',
        phone: '+33 1 73 02 93 93',
        position: 'Premium Account Director',
      },
      status: 'active',
      totalPolicies: 1867,
      activePolicies: 1798,
      claimSettlementRatio: 99.2,
      avgClaimSettlementTime: 2,
      customerRating: 4.9,
      reviewCount: 1076,
      isPopular: true,
      isFeatured: true,
      commission: 20,
      partneredSince: '2019-02-14',
      benefits: [
        'Luxury healthcare',
        'Private rooms guaranteed',
        'Concierge service',
        'Alternative medicine',
      ],
      exclusions: ['War', 'Nuclear risks'],
      documents: [{ name: 'Premium Policy', type: 'pdf', url: '#', size: '5.1 MB' }],
      tags: ['luxury', 'premium', 'concierge', 'private'],
    },
    {
      id: 14,
      companyName: 'Anthem Global',
      companyLogo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=200',
      country: 'United States',
      region: 'Americas',
      planName: 'Global Executive',
      planType: 'premium',
      coverageAmount: 12000000,
      currency: 'USD',
      premium: 6800,
      deductible: 300,
      coinsurance: 5,
      copay: 15,
      coverage: {
        inpatient: true,
        outpatient: true,
        emergency: true,
        dental: true,
        vision: true,
        maternity: true,
        mentalHealth: true,
        prescriptionDrugs: true,
        preventiveCare: true,
        rehabilitation: true,
      },
      networkSize: 45000,
      networkType: 'global',
      claimProcess: 'cashless',
      waitingPeriod: 0,
      contactPerson: {
        name: 'James Wilson',
        email: 'j.wilson@anthem.com',
        phone: '+1 800 331 1476',
        position: 'Executive Account Manager',
      },
      status: 'active',
      totalPolicies: 2745,
      activePolicies: 2634,
      claimSettlementRatio: 99.5,
      avgClaimSettlementTime: 1,
      customerRating: 4.9,
      reviewCount: 1543,
      isPopular: true,
      isFeatured: true,
      commission: 22,
      partneredSince: '2017-08-25',
      benefits: [
        'Executive health services',
        'Annual executive physical',
        'Wellness coaching',
        'Nutritionist access',
      ],
      exclusions: ['Experimental procedures only'],
      documents: [{ name: 'Executive Plan', type: 'pdf', url: '#', size: '4.7 MB' }],
      tags: ['executive', 'premium', 'wellness', 'luxury'],
    },
    {
      id: 15,
      companyName: 'Allianz Worldwide Care',
      companyLogo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200',
      country: 'Ireland',
      region: 'Europe',
      planName: 'Essential Care',
      planType: 'basic',
      coverageAmount: 1200000,
      currency: 'EUR',
      premium: 1450,
      deductible: 1800,
      coinsurance: 30,
      copay: 90,
      coverage: {
        inpatient: true,
        outpatient: false,
        emergency: true,
        dental: false,
        vision: false,
        maternity: false,
        mentalHealth: false,
        prescriptionDrugs: false,
        preventiveCare: false,
        rehabilitation: false,
      },
      networkSize: 5500,
      networkType: 'regional',
      claimProcess: 'reimbursement',
      waitingPeriod: 180,
      contactPerson: {
        name: "Fiona O'Brien",
        email: 'f.obrien@allianzworldwidecare.com',
        phone: '+353 1 630 1301',
        position: 'Sales Representative',
      },
      status: 'inactive',
      totalPolicies: 156,
      activePolicies: 134,
      claimSettlementRatio: 89.2,
      avgClaimSettlementTime: 10,
      customerRating: 3.8,
      reviewCount: 87,
      isPopular: false,
      isFeatured: false,
      commission: 8,
      partneredSince: '2024-01-15',
      benefits: ['Emergency coverage', 'Inpatient care only', 'European network'],
      exclusions: ['Outpatient', 'Dental', 'Vision', 'Maternity', 'Mental health'],
      documents: [{ name: 'Essential Plan', type: 'pdf', url: '#', size: '0.8 MB' }],
      tags: ['basic', 'budget', 'emergency-only'],
    },
  ]);

  const activityLog = ref([
    {
      id: 1,
      action: 'Updated',
      item: 'Cigna Global - International Health Premium',
      user: 'Admin User',
      timestamp: '2025-10-17T16:30:00Z',
      details: 'Updated commission rate to 18%',
    },
    {
      id: 2,
      action: 'Featured',
      item: 'William Russell - Expat Health Plus',
      user: 'Admin User',
      timestamp: '2025-10-17T15:20:00Z',
      details: 'Set as featured plan',
    },
  ]);

  const insuranceStats = computed(() => {
    const totalCompanies = insurances.value.length;
    const activeCompanies = insurances.value.filter((i) => i.status === 'active').length;
    const totalPolicies = insurances.value.reduce((sum, i) => sum + i.totalPolicies, 0);
    const totalActivePolicies = insurances.value.reduce((sum, i) => sum + i.activePolicies, 0);
    const avgSettlementRatio = (
      insurances.value.reduce((sum, i) => sum + i.claimSettlementRatio, 0) / (totalCompanies || 1)
    ).toFixed(1);
    const avgRating = (
      insurances.value.reduce((sum, i) => sum + i.customerRating, 0) / (totalCompanies || 1)
    ).toFixed(1);
    const totalCommission = insurances.value.reduce(
      (sum, i) => sum + (i.commission * i.activePolicies * i.premium) / 100,
      0
    );
    const featuredCount = insurances.value.filter((i) => i.isFeatured).length;
    const popularCount = insurances.value.filter((i) => i.isPopular).length;

    return {
      totalCompanies,
      activeCompanies,
      totalPolicies,
      totalActivePolicies,
      avgSettlementRatio,
      avgRating,
      totalCommission,
      featuredCount,
      popularCount,
    };
  });

  const addInsurance = (insuranceData) => {
    const nextId = Math.max(...insurances.value.map((i) => i.id), 0) + 1;
    const newInsurance = {
      id: nextId,
      totalPolicies: 0,
      activePolicies: 0,
      claimSettlementRatio: 0,
      avgClaimSettlementTime: 0,
      customerRating: 0,
      reviewCount: 0,
      isPopular: false,
      isFeatured: false,
      commission: 10,
      tags: [],
      benefits: [],
      exclusions: [],
      documents: [],
      partneredSince: new Date().toISOString().split('T')[0],
      ...insuranceData,
    };
    insurances.value.unshift(newInsurance);

    activityLog.value.unshift({
      id: activityLog.value.length + 1,
      action: 'Added',
      item: `${newInsurance.companyName} - ${newInsurance.planName}`,
      user: 'Admin User',
      timestamp: new Date().toISOString(),
      details: 'New insurance provider added',
    });

    return newInsurance;
  };

  const updateInsurance = (id, insuranceData) => {
    const index = insurances.value.findIndex((i) => i.id === id);
    if (index !== -1) {
      const oldName = `${insurances.value[index].companyName} - ${insurances.value[index].planName}`;
      insurances.value[index] = {
        ...insurances.value[index],
        ...insuranceData,
      };

      activityLog.value.unshift({
        id: activityLog.value.length + 1,
        action: 'Updated',
        item: oldName,
        user: 'Admin User',
        timestamp: new Date().toISOString(),
        details: 'Insurance provider updated',
      });

      return insurances.value[index];
    }
    return null;
  };

  const deleteInsurance = (id) => {
    const index = insurances.value.findIndex((i) => i.id === id);
    if (index !== -1) {
      const deletedItem = insurances.value[index];
      insurances.value.splice(index, 1);

      activityLog.value.unshift({
        id: activityLog.value.length + 1,
        action: 'Deleted',
        item: `${deletedItem.companyName} - ${deletedItem.planName}`,
        user: 'Admin User',
        timestamp: new Date().toISOString(),
        details: 'Insurance provider removed',
      });

      return true;
    }
    return false;
  };

  const bulkUpdateStatus = (ids, status) => {
    ids.forEach((id) => {
      const insurance = insurances.value.find((i) => i.id === id);
      if (insurance) {
        insurance.status = status;
      }
    });

    activityLog.value.unshift({
      id: activityLog.value.length + 1,
      action: 'Bulk Update',
      item: `${ids.length} providers`,
      user: 'Admin User',
      timestamp: new Date().toISOString(),
      details: `Status changed to ${status}`,
    });
  };

  const bulkDelete = (ids) => {
    const deletedCount = ids.length;
    insurances.value = insurances.value.filter((i) => !ids.includes(i.id));

    activityLog.value.unshift({
      id: activityLog.value.length + 1,
      action: 'Bulk Delete',
      item: `${deletedCount} providers`,
      user: 'Admin User',
      timestamp: new Date().toISOString(),
      details: 'Multiple providers deleted',
    });

    return deletedCount;
  };

  const toggleFeatured = (id) => {
    const insurance = insurances.value.find((i) => i.id === id);
    if (insurance) {
      insurance.isFeatured = !insurance.isFeatured;

      activityLog.value.unshift({
        id: activityLog.value.length + 1,
        action: insurance.isFeatured ? 'Featured' : 'Unfeatured',
        item: `${insurance.companyName} - ${insurance.planName}`,
        user: 'Admin User',
        timestamp: new Date().toISOString(),
        details: `Set featured status to ${insurance.isFeatured}`,
      });
    }
    return insurance;
  };

  const togglePopular = (id) => {
    const insurance = insurances.value.find((i) => i.id === id);
    if (insurance) {
      insurance.isPopular = !insurance.isPopular;

      activityLog.value.unshift({
        id: activityLog.value.length + 1,
        action: insurance.isPopular ? 'Marked Popular' : 'Unmarked Popular',
        item: `${insurance.companyName} - ${insurance.planName}`,
        user: 'Admin User',
        timestamp: new Date().toISOString(),
        details: `Set popular status to ${insurance.isPopular}`,
      });
    }
    return insurance;
  };

  const getInsuranceById = (id) => insurances.value.find((i) => i.id === id) || null;

  return {
    insurances,
    activityLog,
    insuranceStats,
    addInsurance,
    updateInsurance,
    deleteInsurance,
    bulkUpdateStatus,
    bulkDelete,
    toggleFeatured,
    togglePopular,
    getInsuranceById,
  };
};
